source 'https://cdn.cocoapods.org/'

use_frameworks!
platform :ios, '11.0'


target 'ctkit_Example' do
  pod 'ctkit', :path => '../'

  target 'ctkit_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'RxBlocking'
    pod 'RxTest'
    pod 'Mockingjay', :git => 'https://github.com/smaato/Mockingjay.git'
    # '~> 3.0.0-alpha.1'
  end
end
