use_frameworks!

target 'ctkit_Example' do
  pod 'ctkit', :path => '../'

  target 'ctkit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
  end
end
