use_frameworks!

target 'ctkit_Example' do
  pod 'ctkit', :path => '../'

  target 'ctkit_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
    pod 'Mockingjay'
  end
end
