# .circleci/config.yml
version: 2
references:
  container_config: &container_config
    macos:
      xcode: "10.1.0"
    shell: /bin/bash --login -o pipefail
    working_directory: /Users/distiller/project/Example

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - checkout-repo-{{ .Branch }}-{{ .Revision }}
        - checkout-repo-{{ .Branch }}-
        - checkout-repo-
  
  restore_specs: &restore_specs        
    restore_cache:
      keys:
        - checkout-cocoapods-{{ .Branch }}-{{ .Revision }}
        - checkout-cocoapods-{{ .Branch }}-
        - checkout-cocoapods-

jobs:
  provision:
    <<: *container_config
    steps:
      - checkout:
          path: /Users/distiller/project
      - run:
          name: cocoapods specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: install cocoapods
          command: pod install --verbose

      - save_cache:
          key: checkout-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ../

      - persist_to_workspace:
          root: /Users/distiller/project/.cocoapods
          paths:
            - repos

  test:
    <<: *container_config
    steps:
      - *restore_repo
      - run:
          name: fastlane
          command: fastlane tests
      - store_test_results:
          path: fastlane/test_output

  deploy:
    <<: *container_config
    steps:
      - *restore_repo
      - attach_workspace:
          at: /Users/distiller/project/.cocoapods
      - add_ssh_keys
      - run:
          name: keyscan bitbucket
          command: ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts && ssh-add -L
      - run:
          name: pod repo add
          command: pod repo add conneqtech git@bitbucket.org:nfnty_admin/conneqtech-specs.git
      - run:
          working_directory: /Users/distiller/project
          name: pod repo push
          command: pod repo push conneqtech ctkit.podspec

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - provision
      - test:
          requires:
            - provision
      - deploy:
          requires:
            - provision