# .circleci/config.yml

version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/project/Example
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: tests
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Example/Gemfile.lock" }}
      - run: 
          name: bundle check
          working_directory: Example
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Example/Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: cocoapods specs
          working_directory: Example
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: install cocoapods
          working_directory: Example
          command: pod install --verbose
      - run:
          name: fastlane
          working_directory: Example
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan