# # .circleci/config.yml
# version: 2.1
# references:
#   container_config: &container_config
#     macos:
#       xcode: "10.1.0"
#     shell: /bin/bash --login -o pipefail
#     working_directory: /Users/distiller/project/Example
#
#   restore_repo: &restore_repo
#     restore_cache:
#       keys:
#         - checkout-repo-{{ .Branch }}-{{ .Revision }}
#         - checkout-repo-{{ .Branch }}-
#         - checkout-repo-
#
# commands:
#   configure_ssh:
#     description: "Configure SSH keys for Continuous Deployment"
#     steps:
#       - add_ssh_keys
#       - run:
#           name: keyscan bitbucket
#           command: ssh-keyscan -H bitbucket.org >> ~/.ssh/known_hosts
#       - run:
#           name: append git config
#           command: echo -e "[url \"git@bitbucket.org:\"]\n\tinsteadOf = https://bitbucket.org/" >> ~/.gitconfig
#
# jobs:
#   provision:
#     <<: *container_config
#     steps:
#       - checkout:
#           path: /Users/distiller/project
#       - run:
#           name: cocoapods specs
#           command: |
#             curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
#       - run:
#           name: install cocoapods
#           command: pod install --verbose
#
#       - save_cache:
#           key: checkout-repo-{{ .Branch }}-{{ .Revision }}
#           paths:
#             - ../
#
#   test:
#     <<: *container_config
#     steps:
#       - *restore_repo
#       - run:
#           name: fastlane
#           command: fastlane tests
#       - store_test_results:
#           path: fastlane/test_output
#
#   docs:
#     <<: *container_config
#     working_directory: /Users/distiller/project
#     steps:
#       - *restore_repo
#       - configure_ssh
#       - run:
#           name: install jazzy
#           command: sudo gem install jazzy -- --with-sqlite3-lib=/usr/lib
#       - run:
#           name: cocoapods specs
#           command: |
#             curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
#       - run:
#           name: generate docs
#           command: jazzy --podspec ctkit.podspec --output ./docs/public/ios
#       - store_artifacts:
#           path: docs
#
#   deploy:
#     <<: *container_config
#     steps:
#       - *restore_repo
#       - run:
#           name: cocoapods specs
#           command: |
#             curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
#       - configure_ssh
#       - run:
#           name: pod repo add
#           command: pod repo add conneqtech git@bitbucket.org:nfnty_admin/conneqtech-specs.git
#       - run:
#           working_directory: /Users/distiller/project
#           name: pod repo push
#           command: pod repo push conneqtech ctkit.podspec
#
# workflows:
#   version: 2
#   build_test_and_deploy:
#     jobs:
#       - provision
#       - test:
#           requires:
#             - provision
#       - docs:
#           requires:
#             - provision
#             - test
#           filters:
#             tags:
#               only: /.*/
#             branches:
#               only:
#                 - master
#       - deploy:
#           requires:
#             - provision
#             - test
#           filters:
#             tags:
#               only: /.*/
#             branches:
#               only:
#                 - master
