# .circleci/config.yml
version: 2
references:
  container_config: &container_config
    macos:
      xcode: "10.1.0"
    shell: /bin/bash --login -o pipefail
    working_directory: /Users/distiller/project/Example

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - checkout-repo-{{ .Branch }}-{{ .Revision }}
        - checkout-repo-{{ .Branch }}-
        - checkout-repo-

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - checkout:
          path: /Users/distiller/project
      - run:
          name: cocoapods specs
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: install cocoapods
          command: pod install --verbose

      - save_cache:
          key: checkout-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  test:
    <<: *container_config
    steps:
      - *restore_repo
      - run:
          name: fastlane
          command: fastlane tests
      - store_test_results:
          path: fastlane/test_output

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code:
      - test:
        requires:
          - checkout_code