//
//  CTRideServiceTests.swift
//  ctkit_Tests
//
//  Created by Daan van der Jagt on 10/11/2018.
//  Copyright © 2018 CocoaPods. All rights reserved.
//

import Foundation
import Quick
import Nimble
import ctkit
import Mockingjay
import RxSwift

import RxBlocking
import XCTest

class CTRideServiceTests: XCTestCase {
    
    override func setUp() {
        let _ = try! CTUserService().login(email: "paul@conneqtech.com", password: "test").toBlocking().first()!
    }
    
    func testAutogeneratedRides() {
        let subjectUnderTest = try! CTRideService().fetchAllPaginated(withBikeId: 743).toBlocking().first()!
        
        print(subjectUnderTest.data)
    }
    
    func testRideNames() {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss"
        
        for index in 0...23 {
            let currentDateString = "2019-03-01T\(index):00:00"
            
            if let date = dateFormatter.date(from: currentDateString) {
                let ride = CTRideModel(withId: 1, name: "", rideType: "ride.type.autogenerated", startDate: date, endDate: date)
                let key = CTRideService().getTranslationKey(forRide: ride)
                print("Date: \(currentDateString), Key: \(key)")
            }
        }

        // Edge cases
        let morningEdgeCase = "2019-03-01T11:59:59"
        let morningEdgeCaseDate = dateFormatter.date(from: morningEdgeCase)!
        let ride = CTRideModel(withId: 1, name: "", rideType: "ride.type.autogenerated", startDate: morningEdgeCaseDate, endDate: morningEdgeCaseDate)
        let key = CTRideService().getTranslationKey(forRide: ride)

        XCTAssertEqual(key, "ride.name.friday.morning")
    }
}
